"""Initial

Revision ID: ffc1bb249915
Revises: 
Create Date: 2025-07-25 00:00:32.579857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc1bb249915'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('countofsessions_alife_steam', sa.Integer(), nullable=True),
    sa.Column('countofsessions_sinusoid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role'), nullable=True),
    sa.Column('count_of_sessions_alife_steam', sa.Integer(), nullable=True),
    sa.Column('count_of_session_sinusoid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('slot_datetime', sa.DateTime(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELED', name='slot_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('with_subscribtion', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_datetime')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_slots')
    op.drop_table('users')
    op.drop_table('subscriptios')
    op.drop_table('events')
    # ### end Alembic commands ###
